In [1]:
import pandas as pd

In [43]:
df = pd.read_csv("emse19/emse19/emse19/Training Dataset/review_and_label.csv")

In [44]:
df["Label"] = df.Label.str.lower()

In [45]:
df

                                                Reviews  Label
0     I love the app, I have used it for years The o...  usa\n
1     It would be better if they actually released t...  mis\n
2     Needs to be an option to pay monthly, or to op...  mis\n
3     Please let there be a one week free trial I wo...  mis\n
4     Can\'t connect to server. Failed big time. Ple...  sup\n
...                                                 ...    ...
5995  I followed all the instructions airplane mode,...  mis\n
5996          What a disappointment for 4.99 Ugh     \n  mis\n
5997        I hate it ... this app does not work.    \n  usa\n
5998  Im at 28 weeks, and I was able to listen to my...  mis\n
5999  I have had this app downloaded since I was may...    mis

[6000 rows x 2 columns]

In [46]:
df["to_label"] = df["Label"].apply(lambda x: "mis" in x)

In [47]:
to_label = df[df["to_label"]].sample(1000, random_state=0)

In [48]:
to_label["Labeler"] = ""

In [49]:
to_label["Labeler"].iloc[:500] = "Romario"
to_label["Labeler"].iloc[500:] = "Joanna"

C:\Users\Romario\AppData\Local\Temp\ipykernel_17672\1746198666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_label["Labeler"].iloc[:500] = "Romario"
C:\Users\Romario\AppData\Local\Temp\ipykernel_17672\1746198666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  to_label["Labeler"].iloc[500:] = "Joanna"

In [50]:
to_label

,Reviews,Label,to_label,Labeler
449,I give it 5 stars it almost had everything I ...,mis\n,True,Romario
116,I like this app and I segues to make stronger ...,mis\n,True,Romario
5681,So far does everything I want it to. \n,mis\n,True,Romario
4506,This app provides a lot of value for my phone ...,mis\n,True,Romario
4854,This is a wonderful app for figuring out what ...,mis\n,True,Romario
...,...,...,...,...
5598,Thanks Great app does he simple things well. ...,mis\n,True,Joanna
4916,You said you fixed the tracing of comet ISON I...,mis\n,True,Joanna
3241,This App is by far my Go to App for doing art....,mis\n,True,Joanna
3146,Happy to see how fast the crashing issue was f...,mis\n,True,Joanna
152,I've been a user for about 3 years now After n...,mis\n,True,Joanna

In [51]:

to_label["Useful?"] = ""
to_label["Comments"] = ""

In [52]:
to_label

,Reviews,Label,to_label,Labeler,Useful?,Comments
449,I give it 5 stars it almost had everything I ...,mis\n,True,Romario,,
116,I like this app and I segues to make stronger ...,mis\n,True,Romario,,
5681,So far does everything I want it to. \n,mis\n,True,Romario,,
4506,This app provides a lot of value for my phone ...,mis\n,True,Romario,,
4854,This is a wonderful app for figuring out what ...,mis\n,True,Romario,,
...,...,...,...,...,...,...
5598,Thanks Great app does he simple things well. ...,mis\n,True,Joanna,,
4916,You said you fixed the tracing of comet ISON I...,mis\n,True,Joanna,,
3241,This App is by far my Go to App for doing art....,mis\n,True,Joanna,,
3146,Happy to see how fast the crashing issue was f...,mis\n,True,Joanna,,
152,I've been a user for about 3 years now After n...,mis\n,True,Joanna,,

In [55]:
to_label[["Reviews", "Labeler", "Useful?", "Comments"]].to_csv("Manual_labeling_file.csv", index=None)